"""Shared example payloads and helpers for postman updater."""
import json

def ok(data_key, data_val, msg=""):
    return {"success": True, "message": msg, "data": {data_key: data_val}, "meta": {}, "timestamp": "2026-06-12T10:00:00+00:00"}

def list_ok(data_key, data_val, msg=""):
    return {"success": True, "message": msg, "data": {data_key: data_val, "pagination": {"current_page":1,"last_page":1,"per_page":20,"total":1}}, "meta": {}, "timestamp": "2026-06-12T10:00:00+00:00"}

def deleted(msg="Deleted successfully"):
    return {"success": True, "message": msg, "data": None, "meta": {}, "timestamp": "2026-06-12T10:00:00+00:00"}

# ── reusable model shapes ────────────────────────────────────────────────────

DEPT      = {"id":1,"name":"Human Resources","name_en":"Human Resources","name_ar":"الموارد البشرية","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
LOCATION  = {"id":1,"name":"Riyadh","name_en":"Riyadh","name_ar":"الرياض","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
JOB_TYPE  = {"id":1,"name":"Full Time","name_en":"Full Time","name_ar":"دوام كامل","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
JOB = {"id":1,"department":DEPT,"location":LOCATION,"job_type":JOB_TYPE,"title":"Software Engineer","title_en":"Software Engineer","title_ar":"مهندس برمجيات","description":"Build amazing products","description_en":"Build amazing products","description_ar":"بناء منتجات رائعة","image_url":None,"is_active":True,"role_sections":[],"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
CAREER_PAGE = {"id":1,"description":"Join our team","description_en":"Join our team","description_ar":"انضم إلى فريقنا","banner_image_url":None,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
SERVICE = {"id":1,"title":"Digital Transformation","title_en":"Digital Transformation","title_ar":"التحول الرقمي","description":"Desc","description_en":"Desc","description_ar":"وصف","img_url":None,"is_active":True,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
SOLUTION = {**SERVICE, "title":"Cloud Solutions","title_en":"Cloud Solutions","title_ar":"حلول السحابة"}
INDUSTRY = {**SERVICE, "title":"Healthcare","title_en":"Healthcare","title_ar":"الرعاية الصحية"}
BLOG_CAT = {"id":1,"title":"Technology","title_en":"Technology","title_ar":"التقنية","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
BLOG = {"id":1,"category":BLOG_CAT,"title":"AI Trends","title_en":"AI Trends","title_ar":"اتجاهات الذكاء الاصطناعي","content":"Content here","content_en":"Content here","content_ar":"المحتوى هنا","img_url":None,"is_active":True,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
FAQ_CAT = {"id":1,"title":"General","title_en":"General","title_ar":"عام","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
FAQ = {"id":1,"category":FAQ_CAT,"title":"What is Industry360?","title_en":"What is Industry360?","title_ar":"ما هو إندستري 360؟","description":"A leading platform","description_en":"A leading platform","description_ar":"منصة رائدة","is_active":True,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
PARTNER = {"id":1,"name":"Partner Co","name_en":"Partner Co","name_ar":"شركة الشريك","img_url":None,"is_active":True,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
CASE_STUDY = {"id":1,"title":"Digital Bank","title_en":"Digital Bank","title_ar":"البنك الرقمي","description":"Case study desc","description_en":"Case study desc","description_ar":"وصف","img_url":None,"is_active":True,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
CONTACT_IND = {"id":1,"title":"Finance","title_en":"Finance","title_ar":"المالية","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
CONTACT_SVC = {"id":1,"title":"Consulting","title_en":"Consulting","title_ar":"الاستشارات","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
CONTACT_SOL = {"id":1,"title":"ERP Implementation","title_en":"ERP Implementation","title_ar":"تطبيق نظام تخطيط الموارد","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
VISION_MSG = {"id":1,"title":"Our Vision","title_en":"Our Vision","title_ar":"رؤيتنا","description":"Leading digital transformation","description_en":"Leading digital transformation","description_ar":"قيادة التحول الرقمي","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
VISION_SETTING = {"id":1,"title":"Vision & Message","title_en":"Vision & Message","title_ar":"الرؤية والرسالة","description":"Our core values","description_en":"Our core values","description_ar":"قيمنا الجوهرية","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
METHODOLOGY = {"id":1,"title":"Agile","title_en":"Agile","title_ar":"أجايل","description":"Fast iterations","description_en":"Fast iterations","description_ar":"تكرارات سريعة","order":1,"is_active":True,"img_url":None,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
METHODOLOGY_SETTING = {"id":1,"title":"Our Methodology","title_en":"Our Methodology","title_ar":"منهجيتنا","description":"How we work","description_en":"How we work","description_ar":"كيف نعمل","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
TEAM_SETTING = {"id":1,"title":"Our Team","title_en":"Our Team","title_ar":"فريقنا","description":"Meet the team","description_en":"Meet the team","description_ar":"تعرف على الفريق","created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
TEAM_MEMBER = {"id":1,"title":"John Doe","title_en":"John Doe","title_ar":"جون دو","position":"CEO","position_en":"CEO","position_ar":"الرئيس التنفيذي","description":"Experienced leader","description_en":"Experienced leader with 15+ years.","description_ar":"قائد متمرس بأكثر من 15 عامًا.","social_links":[{"platform":"linkedin","url":"https://linkedin.com/in/johndoe"},{"platform":"twitter","url":"https://twitter.com/johndoe"}],"img_path":"team_members/photo.jpg","img_url":"http://localhost:8000/storage/team_members/photo.jpg","is_active":True,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
ABOUT_US = {"id":1,"title":"About Industry360","title_en":"About Industry360","title_ar":"عن إندستري 360","description":"We are a leading tech company.","description_en":"We are a leading tech company.","description_ar":"نحن شركة تقنية رائدة.","sub_title":"What We Achieved","sub_title_en":"What We Achieved","sub_title_ar":"ما حققناه","sub_description":"Our numbers speak for themselves.","sub_description_en":"Our numbers speak for themselves.","sub_description_ar":"أرقامنا تتحدث عن نفسها.","percentage_title_1":"Customer Satisfaction","percentage_title_1_en":"Customer Satisfaction","percentage_title_1_ar":"رضا العملاء","percentage_description_1":"Clients who rate us 5 stars","percentage_description_1_en":"Clients who rate us 5 stars","percentage_description_1_ar":"عملاء يمنحوننا 5 نجوم","percentage_value_1":95,"percentage_title_2":"Project Success","percentage_title_2_en":"Project Success","percentage_title_2_ar":"نجاح المشاريع","percentage_description_2":"On-time delivery","percentage_description_2_en":"On-time delivery","percentage_description_2_ar":"التسليم في الوقت المحدد","percentage_value_2":88,"percentage_title_3":"Growth Rate","percentage_title_3_en":"Growth Rate","percentage_title_3_ar":"معدل النمو","percentage_description_3":"Year-over-year growth","percentage_description_3_en":"Year-over-year growth","percentage_description_3_ar":"النمو السنوي","percentage_value_3":72,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
PACKAGE = {"id":1,"service_id":1,"service_type":"service","title":"Basic Package","title_en":"Basic Package","title_ar":"الباقة الأساسية","description":"Includes core features","description_en":"Includes core features","description_ar":"يشمل الميزات الأساسية","is_active":True,"service":SERVICE,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
CONTACT_PKG = {"id":1,"title":"Contact Package","title_en":"Contact Package","title_ar":"باقة التواصل","description":"Contact features","description_en":"Contact features","description_ar":"ميزات التواصل","is_active":True,"created_at":"2026-06-12 10:00:00","updated_at":"2026-06-12 10:00:00"}
APPLICATION = {"id":1,"job":JOB,"full_name":"Ahmed Ali","email":"ahmed@example.com","phone":"+966501234567","cv_url":None,"created_at":"2026-06-12 10:00:00"}
ADMIN_ME = {"id":1,"full_name":"Admin User","email":"admin@example.com","role":"admin-manager","permissions":["view-dashboard","view-users"]}
